### ISSUE TITLE
请问 我安装后不能使用怎么办

### ISSUE THREAD

**Issue by duoshoumiao** [Lanly109/headimg_generator#43]
aiocache                    0.11.1
aiocqhttp                   1.4.3
aiofiles                    0.8.0
aiohttp                     3.8.1
aiosignal                   1.2.0
altgraph                    0.17.2
annotated-types             0.5.0
ansimarkup                  1.5.0
anyio                       3.7.1
appdirs                     1.4.4
APScheduler                 3.9.1
arrow                       0.14.0
async-generator             1.10
async-timeout               4.0.2
attrs                       21.4.0
backports.zoneinfo          0.2.1
bbcode                      1.1.0
beautifulsoup4              4.11.0
better-exceptions-fork      0.2.1.post6
binaryornot                 0.4.4
blinker                     1.4
bs4                         0.0.1
CacheControl                0.12.11
cachy                       0.3.0
cairocffi                   1.3.0
CairoSVG                    2.5.2
cattrs                      1.10.0
certifi                     2022.5.18.1
cffi                        1.15.0
chardet                     3.0.4
charset-normalizer          2.0.12
cleo                        0.8.1
click                       8.1.3
clikit                      0.6.2
cloudscraper                1.2.48
colorama                    0.4.4
cookiecutter                1.7.3
crashtest                   0.3.1
cryptography                37.0.4
cssselect2                  0.6.0
cycler                      0.11.0
dateparser                  1.1.8
defusedxml                  0.7.1
demjson                     2.2.4
dill                        0.3.5.1
distlib                     0.3.5
emoji                       1.7.0
et-xmlfile                  1.1.0
exceptiongroup              1.1.1
expiringdict                1.2.2
fastapi                     0.103.1
feedparser                  6.0.0
ffmpeg                      1.4
filelock                    3.7.1
filetype                    1.2.0
fonttools                   4.33.3
frozenlist                  1.3.0
future                      0.18.2
fuzzywuzzy                  0.18.0
gitdb                       4.0.9
greenlet                    1.1.2
h11                         0.12.0
h2                          4.1.0
hpack                       4.0.0
html5lib                    1.1
httpcore                    0.15.0
httptools                   0.4.0
httpx                       0.23.0
hypercorn                   0.13.2
hyperframe                  6.0.1
idna                        3.3
imageio                     2.19.2
importlib-metadata          4.12.0
itsdangerous                2.1.2
Jinja2                      2.11.3
jinja2-time                 0.2.0
jmespath                    1.0.0
keyring                     23.7.0
kiwisolver                  1.4.2
kth-timeoutdecorator        0.0.5
langid                      1.1.6
lockfile                    0.12.2
loguru                      0.6.0
logzero                     1.7.0
lxml                        4.9.1
Markdown                    3.3.4
markdown-it-py              3.0.0
MarkupSafe                  2.0.1
matplotlib                  3.5.2
mdurl                       0.1.2
meme-generator              0.0.15
msgpack                     1.0.2
msgpack-python              0.5.6
multidict                   4.7.6
multiprocess                0.70.13
nb-cli                      0.6.7
nest-asyncio                1.5.5
nonebot                     1.9.1
numpy                       1.20.3
oauthlib                    3.2.0
opencc-python-reimplemented 0.1.6
opencv-python-headless      4.1.2.30
outcome                     1.2.0
packaging                   20.9
pastel                      0.2.1
pathlib                     1.0.1
peewee                      3.13.0
pefile                      2021.9.3
pexpect                     4.8.0
pil-utils                   0.1.8
Pillow                      9.4.0
pip                         23.0.1
PixivPy                     3.6.2
pkginfo                     1.8.3
platformdirs                2.5.2
playwright                  1.20.1
poetry                      1.1.14
poetry-core                 1.0.8
pox                         0.3.1
poyo                        0.5.0
ppft                        1.7.6.5
prettytable                 3.3.0
priority                    2.0.0
prompt-toolkit              3.0.30
psutil                      5.9.1
ptyprocess                  0.7.0
pycparser                   2.21
pycryptodome                3.14.1
pydantic                    1.9.1
pydantic_core               2.6.3
pydub                       0.25.1
pyee                        8.1.0
pyfiglet                    0.8.post1
Pygments                    2.16.1
pygtrie                     2.4.2
pyinstaller                 5.1
pyinstaller-hooks-contrib   2022.5
pylev                       1.4.0
pyOpenSSL                   22.0.0
pyparsing                   3.0.9
pypinyin                    0.49.0
PySocks                     1.7.1
python-dateutil             2.8.2
python-dotenv               0.20.0
python-engineio             3.14.2
python-multipart            0.0.6
python-slugify              6.1.2
python-socketio             4.6.1
pytoml                      0.1.21
pytz                        2022.1
pytz-deprecation-shim       0.1.0.post0
pywin32-ctypes              0.2.0
PyYAML                      6.0b1
pyyaml_env_tag              0.1
pyzbar                      0.1.9
quart                       0.17.0
regex                       2023.8.8
requests                    2.28.2
requests-cache              0.9.4
requests-oauthlib           1.3.1
requests-toolbelt           0.9.1
retrying                    1.3.3
rfc3986                     1.5.0
rich                        13.5.2
selenium                    4.3.0
setuptools                  47.1.0
sgmllib3k                   1.0.0
shellingham                 1.5.0
six                         1.16.0
smmap                       5.0.0
sniffio                     1.2.0
sogou-tr                    0.1.1
sogou-tr-free               0.0.11
some-package                0.1
sortedcontainers            2.4.0
soupsieve                   2.3.2.post1
sqlitedict                  2.1.0
starlette                   0.27.0
text-unidecode              1.3
thulac                      0.2.1
tinycss2                    1.1.1
tinydb                      4.7.0
toml                        0.10.2
tomli                       2.0.1
tomlkit                     0.10.2
tqdm                        4.65.0
trio                        0.21.0
trio-websocket              0.9.2
TwitterAPI                  2.7.12
typing_extensions           4.7.1
tzdata                      2022.1
tzlocal                     4.2
ujson                       5.3.0
url-normalize               1.4.3
urllib3                     1.26.9
urllib3-secure-extra        0.1.0
urwid                       2.1.2
uvicorn                     0.23.2
virtualenv                  20.16.3
watchfiles                  0.16.1
wcwidth                     0.2.5
webencodings                0.5.1
websocket-client            1.3.3
websockets                  10.1
Werkzeug                    2.1.2
win32-setctime              1.1.0
wsproto                     1.1.0
yarl                        1.7.2
zhconv                      1.4.3
zipp                        3.8.1

[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip
  File "C:\Users\Administrator\Desktop\HoshinoBot-master - 1\HoshinoBot-master\hoshino\modules\headimg_generator\__init__.py", line 17, in <module>
    from meme_generator.download import check_resources
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\meme_generator\__init__.py", line 4, in <module>
    from meme_generator.manager import add_meme as add_meme
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\meme_generator\manager.py", line 10, in <module>
    from .meme import Meme, MemeArgsType, MemeFunction, MemeParamsType
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\meme_generator\meme.py", line 37, in <module>
    class UserInfo(BaseModel):

**Comment by duoshoumiao** [comment]
还是搞不懂  而且不能跟截图怎么拆兼容

**Comment by duoshoumiao** [comment]
[2023-09-11 12:02:18,203 nonebot] ERROR: Failed to import and load "hoshino.modules.picfinder_take.picfinder_take", error: No module named 'hoshino.modules.picfinder_take.picfinder_take'
[2023-09-11 12:02:18,203 nonebot] ERROR: No module named 'hoshino.modules.picfinder_take.picfinder_take'
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 419, in _load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'hoshino.modules.picfinder_take.picfinder_take'
[2023-09-11 12:02:18,203 nonebot] ERROR: Failed to import and load "hoshino.modules.fendao.fendao", error: Service name "分刀" already exist!
[2023-09-11 12:02:18,203 nonebot] ERROR: Service name "分刀" already exist!
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 419, in _load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\HoshinoBot-master - 1\HoshinoBot-master\hoshino\modules\fendao\fendao\__init__.py", line 88, in <module>
    sv = Service('分刀', enable_on_default=True, help_=f"{helpText1}\n\n{helpText2}")
  File "C:\Users\Administrator\Desktop\HoshinoBot-master - 1\HoshinoBot-master\hoshino\service.py", line 128, in __init__
    assert self.name not in _loaded_services, f'Service name "{self.name}" already exist!'
AssertionError: Service name "分刀" already exist!
[2023-09-11 12:02:18,219 nonebot] ERROR: Failed to import and load "hoshino.modules.fendao.timeaxis", error: No module named 'hoshino.modules.util'
[2023-09-11 12:02:18,219 nonebot] ERROR: No module named 'hoshino.modules.util'
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 419, in _load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\HoshinoBot-master - 1\HoshinoBot-master\hoshino\modules\fendao\timeaxis.py", line 7, in <module>
    from ..util.tools import lap2stage, stage_dict
ModuleNotFoundError: No module named 'hoshino.modules.util'
[2023-09-11 12:02:18,353 nonebot] ERROR: Failed to import and load "hoshino.modules.headimg_generator.config", error: issubclass() arg 1 must be a class
[2023-09-11 12:02:18,353 nonebot] ERROR: issubclass() arg 1 must be a class
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 419, in _load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\HoshinoBot-master - 1\HoshinoBot-master\hoshino\modules\headimg_generator\__init__.py", line 17, in <module>
    from meme_generator.download import check_resources
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\meme_generator\__init__.py", line 4, in <module>
    from meme_generator.manager import add_meme as add_meme
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\meme_generator\manager.py", line 10, in <module>
    from .meme import Meme, MemeArgsType, MemeFunction, MemeParamsType
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\meme_generator\meme.py", line 37, in <module>
    class UserInfo(BaseModel):
  File "pydantic\main.py", line 205, in pydantic.main.ModelMetaclass.__new__
  File "pydantic\fields.py", line 491, in pydantic.fields.ModelField.infer
  File "pydantic\fields.py", line 421, in pydantic.fields.ModelField.__init__
  File "pydantic\fields.py", line 537, in pydantic.fields.ModelField.prepare
  File "pydantic\fields.py", line 641, in pydantic.fields.ModelField._type_analysis
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
[2023-09-11 12:02:18,369 nonebot] ERROR: Failed to import and load "hoshino.modules.headimg_generator.data_source", error: issubclass() arg 1 must be a class
[2023-09-11 12:02:18,369 nonebot] ERROR: issubclass() arg 1 must be a class
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 419, in _load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\HoshinoBot-master - 1\HoshinoBot-master\hoshino\modules\headimg_generator\__init__.py", line 17, in <module>
    from meme_generator.download import check_resources
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\meme_generator\__init__.py", line 4, in <module>
    from meme_generator.manager import add_meme as add_meme
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\meme_generator\manager.py", line 10, in <module>
    from .meme import Meme, MemeArgsType, MemeFunction, MemeParamsType
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\meme_generator\meme.py", line 37, in <module>
    class UserInfo(BaseModel):
  File "pydantic\main.py", line 205, in pydantic.main.ModelMetaclass.__new__
  File "pydantic\fields.py", line 491, in pydantic.fields.ModelField.infer
  File "pydantic\fields.py", line 421, in pydantic.fields.ModelField.__init__
  File "pydantic\fields.py", line 537, in pydantic.fields.ModelField.prepare
  File "pydantic\fields.py", line 641, in pydantic.fields.ModelField._type_analysis
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
[2023-09-11 12:02:18,369 nonebot] ERROR: Failed to import and load "hoshino.modules.headimg_generator.depends", error: issubclass() arg 1 must be a class
[2023-09-11 12:02:18,369 nonebot] ERROR: issubclass() arg 1 must be a class
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 419, in _load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\HoshinoBot-master - 1\HoshinoBot-master\hoshino\modules\headimg_generator\__init__.py", line 17, in <module>
    from meme_generator.download import check_resources
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\meme_generator\__init__.py", line 4, in <module>
    from meme_generator.manager import add_meme as add_meme
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\meme_generator\manager.py", line 10, in <module>
    from .meme import Meme, MemeArgsType, MemeFunction, MemeParamsType
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\meme_generator\meme.py", line 37, in <module>
    class UserInfo(BaseModel):
  File "pydantic\main.py", line 205, in pydantic.main.ModelMetaclass.__new__
  File "pydantic\fields.py", line 491, in pydantic.fields.ModelField.infer
  File "pydantic\fields.py", line 421, in pydantic.fields.ModelField.__init__
  File "pydantic\fields.py", line 537, in pydantic.fields.ModelField.prepare
  File "pydantic\fields.py", line 641, in pydantic.fields.ModelField._type_analysis
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
[2023-09-11 12:02:18,384 nonebot] ERROR: Failed to import and load "hoshino.modules.headimg_generator.exception", error: issubclass() arg 1 must be a class
[2023-09-11 12:02:18,384 nonebot] ERROR: issubclass() arg 1 must be a class
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 419, in _load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\HoshinoBot-master - 1\HoshinoBot-master\hoshino\modules\headimg_generator\__init__.py", line 17, in <module>
    from meme_generator.download import check_resources
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\meme_generator\__init__.py", line 4, in <module>
    from meme_generator.manager import add_meme as add_meme
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\meme_generator\manager.py", line 10, in <module>
    from .meme import Meme, MemeArgsType, MemeFunction, MemeParamsType
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\meme_generator\meme.py", line 37, in <module>
    class UserInfo(BaseModel):
  File "pydantic\main.py", line 205, in pydantic.main.ModelMetaclass.__new__
  File "pydantic\fields.py", line 491, in pydantic.fields.ModelField.infer
  File "pydantic\fields.py", line 421, in pydantic.fields.ModelField.__init__
  File "pydantic\fields.py", line 537, in pydantic.fields.ModelField.prepare
  File "pydantic\fields.py", line 641, in pydantic.fields.ModelField._type_analysis
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
[2023-09-11 12:02:18,384 nonebot] ERROR: Failed to import and load "hoshino.modules.headimg_generator.manager", error: issubclass() arg 1 must be a class
[2023-09-11 12:02:18,384 nonebot] ERROR: issubclass() arg 1 must be a class
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 419, in _load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\HoshinoBot-master - 1\HoshinoBot-master\hoshino\modules\headimg_generator\__init__.py", line 17, in <module>
    from meme_generator.download import check_resources
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\meme_generator\__init__.py", line 4, in <module>
    from meme_generator.manager import add_meme as add_meme
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\meme_generator\manager.py", line 10, in <module>
    from .meme import Meme, MemeArgsType, MemeFunction, MemeParamsType
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\meme_generator\meme.py", line 37, in <module>
    class UserInfo(BaseModel):
  File "pydantic\main.py", line 205, in pydantic.main.ModelMetaclass.__new__
  File "pydantic\fields.py", line 491, in pydantic.fields.ModelField.infer
  File "pydantic\fields.py", line 421, in pydantic.fields.ModelField.__init__
  File "pydantic\fields.py", line 537, in pydantic.fields.ModelField.prepare
  File "pydantic\fields.py", line 641, in pydantic.fields.ModelField._type_analysis
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
[2023-09-11 12:02:18,400 nonebot] ERROR: Failed to import and load "hoshino.modules.headimg_generator.meme_optional", error: issubclass() arg 1 must be a class
[2023-09-11 12:02:18,400 nonebot] ERROR: issubclass() arg 1 must be a class
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 419, in _load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\HoshinoBot-master - 1\HoshinoBot-master\hoshino\modules\headimg_generator\__init__.py", line 17, in <module>
    from meme_generator.download import check_resources
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\meme_generator\__init__.py", line 4, in <module>
    from meme_generator.manager import add_meme as add_meme
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\meme_generator\manager.py", line 10, in <module>
    from .meme import Meme, MemeArgsType, MemeFunction, MemeParamsType
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\meme_generator\meme.py", line 37, in <module>
    class UserInfo(BaseModel):
  File "pydantic\main.py", line 205, in pydantic.main.ModelMetaclass.__new__
  File "pydantic\fields.py", line 491, in pydantic.fields.ModelField.infer
  File "pydantic\fields.py", line 421, in pydantic.fields.ModelField.__init__
  File "pydantic\fields.py", line 537, in pydantic.fields.ModelField.prepare
  File "pydantic\fields.py", line 641, in pydantic.fields.ModelField._type_analysis
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
[2023-09-11 12:02:18,400 nonebot] ERROR: Failed to import and load "hoshino.modules.headimg_generator.utils", error: issubclass() arg 1 must be a class
[2023-09-11 12:02:18,400 nonebot] ERROR: issubclass() arg 1 must be a class
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 419, in _load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\HoshinoBot-master - 1\HoshinoBot-master\hoshino\modules\headimg_generator\__init__.py", line 17, in <module>
    from meme_generator.download import check_resources
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\meme_generator\__init__.py", line 4, in <module>
    from meme_generator.manager import add_meme as add_meme
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\meme_generator\manager.py", line 10, in <module>
    from .meme import Meme, MemeArgsType, MemeFunction, MemeParamsType
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\meme_generator\meme.py", line 37, in <module>
    class UserInfo(BaseModel):
  File "pydantic\main.py", line 205, in pydantic.main.ModelMetaclass.__new__
  File "pydantic\fields.py", line 491, in pydantic.fields.ModelField.infer
  File "pydantic\fields.py", line 421, in pydantic.fields.ModelField.__init__
  File "pydantic\fields.py", line 537, in pydantic.fields.ModelField.prepare
  File "pydantic\fields.py", line 641, in pydantic.fields.ModelField._type_analysis
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class

**Comment by Lanly109** [comment]
昨天貌似在群里看见了讨论，`typing-extensions`版本降到4.3.0可以解决

**Comment by duoshoumiao** [comment]
> 昨天貌似在群里看见了讨论，`typing-extensions`版本降到4.3.0可以解决

大群说是拉不到最新版本，只要文件夹里文件覆盖成下载时候的状态就行，我试了一下还真的是

**Comment by duoshoumiao** [comment]
> 昨天貌似在群里看见了讨论，`typing-extensions`版本降到4.3.0可以解决但是我不想每次重启都覆盖备份  我按你的试试

**Comment by duoshoumiao** [comment]
> 昨天貌似在群里看见了讨论，`typing-extensions`版本降到4.3.0可以解决

试了一下。对我这边不管用

**Comment by duoshoumiao** [comment]
> 昨天貌似在群里看见了讨论，`typing-extensions`版本降到4.3.0可以解决

但是吧config.yml删了就能用了
