### ISSUE TITLE
典中典无法使用，求助

### ISSUE THREAD

**Issue by duoshoumiao** [Lanly109/headimg_generator#46]
![image](https://github.com/Lanly109/headimg_generator/assets/94856184/319cc195-9933-43dc-a2df-ff82f2cb5672)
并没有什么实质报错记录

**Comment by duoshoumiao** [comment]
有报错了
[2023-09-13 09:58:38,691 nonebot] INFO: Self: 270974535, Message 240206935 from 645364231@[群:717297973]: '表情详情 典中典'
[2023-09-13 09:58:38,691 头像表情包] INFO: Message 240206935 triggered info_cmd.
[2023-09-13 09:58:39,294 头像表情包] ERROR: <class 'meme_generator.exception.MemeGeneratorException'> occured when info_cmd handling message 240206935.
[2023-09-13 09:58:39,294 头像表情包] ERROR: Error in meme_generator: The `baidu_trans_appid` or `baidu_trans_apikey` is not set.Please check your config file!
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\HoshinoBot-master - 1\HoshinoBot-master\hoshino\msghandler.py", line 21, in handle_message
    await service_func.func(bot, event)
  File "C:\Users\Administrator\Desktop\HoshinoBot-master - 1\HoshinoBot-master\hoshino\modules\headimg_generator\__init__.py", line 122, in info_cmd
    img = await meme.generate_preview()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\meme_generator\meme.py", line 185, in generate_preview
    return await _generate_preview(default_images, default_texts)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\meme_generator\meme.py", line 180, in _generate_preview
    return await self.__call__(images=images, texts=texts, args=args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\meme_generator\meme.py", line 143, in __call__
    return await cast(Callable[..., Awaitable[BytesIO]], self.function)(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\meme_generator\memes\dianzhongdian\__init__.py", line 48, in dianzhongdian
    trans = await translate(text, lang_to="jp")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\meme_generator\utils.py", line 320, in translate
    raise MemeGeneratorException(
meme_generator.exception.MemeGeneratorException: Error in meme_generator: The `baidu_trans_appid` or `baidu_trans_apikey` is not set.Please check your config file!

**Comment by Lanly109** [comment]
meme_generator插件更新了，配置方法发生了变化，具体可以参考[这里](https://github.com/MeetWq/meme-generator#配置)，baidu的apikey在`config.toml`里配置，晚点我会更新下readme

**Comment by duoshoumiao** [comment]
> meme_generator插件更新了，配置方法发生了变化，具体可以参考[这里](https://github.com/MeetWq/meme-generator#配置)，baidu的apikey在`config.toml`里配置，晚点我会更新下readme

👌

**Comment by kcn3388** [comment]
Complete in #47
