### ISSUE TITLE
AttributeError: 'Event' object has no attribute 'to_me' 

### ISSUE THREAD

**Issue by WindStill** [Lanly109/headimg_generator#48]
Event对象没有to_me属性，把event.to_me换成event['to_me']也不行。这个地方的判断有没有其他方式实现？

![71DFBD1AC1AAF24087E4C2106F5337B1](https://github.com/Lanly109/headimg_generator/assets/958456/f0602500-e759-4f4d-a1b4-ee703dfcefa1)

```
[2023-11-30 17:52:58,788 头像表情包] ERROR: <class 'AttributeError'> occured when
 handle handling message 1740221763.                                             
[2023-11-30 17:52:58,788 头像表情包] ERROR: 'Event' object has no attribute 'to_m
e'                                                                               
Traceback (most recent call last):                                               
  File "/HoshinoBot/hoshino/service.py", line 189, in wrapper                    
    return await func(self.bot, ctx)                                             
  File "/HoshinoBot/hoshino/modules/headimg_generator/__init__.py", line 332, in 
handle                                                                           
    split_msg = await split_msg_v11(bot, ev, msg, meme, trigger)                 
  File "/HoshinoBot/hoshino/modules/headimg_generator/depends.py", line 73, in sp
lit_msg_v11                                                                      
    restore_last_at_me_seg(event, msg)                                           
  File "/HoshinoBot/hoshino/modules/headimg_generator/depends.py", line 29, in re
store_last_at_me_seg                                                             
    if event.to_me:                                                              
AttributeError: 'Event' object has no attribute 'to_me' 
```

**Comment by Lanly109** [comment]
`to_me`是`nonebot2`才有的，这里貌似不需要`restore_last_at_me_seg `这个函数，它貌似不会吞掉`at`的消息，不需要`restore`

**Comment by WindStill** [comment]
> `to_me`是`nonebot2`才有的，这里貌似不需要`restore_last_at_me_seg `这个函数，它貌似不会吞掉`at`的消息，不需要`restore`

好的，多谢。已经去掉了 `restore_last_at_me_seg`
