### ISSUE TITLE
这个报错重装依赖也运行不起来

### ISSUE THREAD

**Issue by duoshoumiao** [Lanly109/headimg_generator#51]
24-02-14 15:45:44,723 nonebot] ERROR: Failed to import and load "hoshino.modules.headimg_generator.utils", error: issubclass() arg 1 must be a class
[2024-02-14 15:45:44,723 nonebot] ERROR: issubclass() arg 1 must be a class
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 419, in _load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\HoshinoBot-master - 1\HoshinoBot-master\hoshino\modules\headimg_generator\__init__.py", line 17, in <module>
    from meme_generator.download import check_resources
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\meme_generator\__init__.py", line 4, in <module>
    from meme_generator.manager import add_meme as add_meme
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\meme_generator\manager.py", line 10, in <module>
    from .meme import Meme, MemeArgsType, MemeFunction, MemeParamsType
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\meme_generator\meme.py", line 37, in <module>
    class UserInfo(BaseModel):
  File "pydantic\main.py", line 198, in pydantic.main.ModelMetaclass.__new__
  File "pydantic\fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic\fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic\fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic\fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class

**Comment by duoshoumiao** [comment]
升级了pydantic==2.3.0就搞定了
