### ISSUE TITLE
求救

### ISSUE THREAD

**Issue by howfer** [Lanly109/headimg_generator#58]
指令随机表情或者是带图片的，会引发如下错误
[2024-10-22 11:32:28,216 头像表情包] ERROR: <class 'KeyError'> occured when handle handling message -2146400747.
[2024-10-22 11:32:28,216] ERROR in service: <class 'KeyError'> occured when handle handling message -2146400747.
[2024-10-22 11:32:28,217 头像表情包] ERROR: 'the key "subType" is not allowed'
Traceback (most recent call last):
  File "/root/tujibot/hoshino/service.py", line 188, in wrapper
    return await func(self.bot, ctx)
  File "/root/tujibot/hoshino/modules/headimg_generator/__init__.py", line 260, in handle
    msg: Message = copy.deepcopy(ev.message)
  File "/usr/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.9/copy.py", line 287, in _reconstruct
    item = deepcopy(item, memo)
  File "/usr/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.9/copy.py", line 297, in _reconstruct
    y[key] = value
  File "/usr/local/lib/python3.9/dist-packages/aiocqhttp/message.py", line 99, in __setitem__
    raise KeyError(f'the key "{key}" is not allowed')
KeyError: 'the key "subType" is not allowed'
[2024-10-22 11:32:28,217] ERROR in service: 'the key "subType" is not allowed'
Traceback (most recent call last):
  File "/root/tujibot/hoshino/service.py", line 188, in wrapper
    return await func(self.bot, ctx)
  File "/root/tujibot/hoshino/modules/headimg_generator/__init__.py", line 260, in handle
    msg: Message = copy.deepcopy(ev.message)
  File "/usr/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.9/copy.py", line 287, in _reconstruct
    item = deepcopy(item, memo)
  File "/usr/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.9/copy.py", line 297, in _reconstruct
    y[key] = value
  File "/usr/local/lib/python3.9/dist-packages/aiocqhttp/message.py", line 99, in __setitem__
    raise KeyError(f'the key "{key}" is not allowed')
KeyError: 'the key "subType" is not allowed'

aiohttp为1.4.4

**Comment by kcn3388** [comment]
无法复现，请尝试更新到最新版本代码再试试，有需要请打包一份当前代码上来debug
