### ISSUE TITLE
[Bug] error: cannot import name 'MessageSegment' from 'hoshino'

### ISSUE THREAD

**Issue by Yoruko-Sugar** [Lanly109/headimg_generator#59]
[2024-12-03 23:26:26,353 nonebot] ERROR: Failed to import and load "hoshino.modules.headimg_generator.config", error: cannot import name 'MessageSegment' from 'hoshino' (C:\Users\Administrator\Desktop\My_Hoshino-main\My_Hoshino-main\hoshino\__init__.py)
[2024-12-03 23:26:26,353 nonebot] ERROR: cannot import name 'MessageSegment' from 'hoshino' (C:\Users\Administrator\Desktop\My_Hoshino-main\My_Hoshino-main\hoshino\__init__.py)
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin.py", line 419, in _load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\My_Hoshino-main\My_Hoshino-main\hoshino\modules\headimg_generator\__init__.py", line 24, in <module>
    from .depends import split_msg_v11
  File "C:\Users\Administrator\Desktop\My_Hoshino-main\My_Hoshino-main\hoshino\modules\headimg_generator\depends.py", line 22, in <module>
    from .utils import split_text
  File "C:\Users\Administrator\Desktop\My_Hoshino-main\My_Hoshino-main\hoshino\modules\headimg_generator\utils.py", line 12, in <module>
    from hoshino import MessageSegment
ImportError: cannot import name 'MessageSegment' from 'hoshino' (C:\Users\Administrator\Desktop\My_Hoshino-main\My_Hoshino-main\hoshino\__init__.py)

**Comment by Yoruko-Sugar** [comment]
请问是我哪里有问题吗，在hoshino的_init_.py没有找到可以用来导入的MessageSegment

**Comment by kcn3388** [comment]
[utils.py](https://github.com/Lanly109/headimg_generator/blob/dd28885ecc07d3cf911f6e7c173240b1481cf049/utils.py#L12)
改为

```python
from hoshino.typing import MessageSegment
```

**Comment by Yoruko-Sugar** [comment]
已验证修复，thanks
