### ISSUE TITLE
'str' object has no attribute 'parent'

### ISSUE THREAD

**Issue by shirleygrey** [Lanly109/headimg_generator#8]
不知道是不是高并发导致的问题。。

[2022-06-21 14:11:00,305 头像表情包] ERROR: 'str' object has no attribute 'parent'
Traceback (most recent call last):
  File "/root/mybot/hoshino/msghandler.py", line 28, in handle_message
    await service_func.func(bot, event)
  File "/root/mybot/hoshino/service.py", line 219, in wrapper
    return await func(bot, event)
  File "/root/mybot/hoshino/modules/headimg_generator/__init__.py", line 18, in help
  File "/root/mybot/hoshino/modules/headimg_generator/utils.py", line 425, in help_image
  File "/root/mybot/hoshino/modules/headimg_generator/utils.py", line 369, in load_font
  File "/usr/local/lib/python3.9/site-packages/aiocache/decorators.py", line 93, in wrapper
    return await self.decorator(f, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/aiocache/decorators.py", line 108, in decorator
    result = await f(*args, **kwargs)
  File "/root/mybot/hoshino/modules/headimg_generator/download.py", line 55, in get_font
  File "/root/mybot/hoshino/modules/headimg_generator/download.py", line 36, in get_resource
AttributeError: 'str' object has no attribute 'parent'

**Comment by shirleygrey** [comment]
好像是误删了资源。。
